name: Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: windows-2022
    
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-java@v4
       with:
         java-version: 20
         distribution: "oracle"
     - run: mvn verify
     - uses: actions/upload-artifact@v4
       with:
         name: plataformer
         path: 'target/release'
     - uses: AButler/upload-release-assets@v3.0
       with:
         files: 'target/release/*'
         repo-token: ${{ secrets.GITHUB_TOKEN }}